version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flowbit-backend
    ports:
      - "8000:8000"
    volumes:
      - ./memory.db:/app/memory.db
      - ./output_logs:/app/output_logs
    restart: unless-stopped
    networks:
      - flowbit-network

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: flowbit-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    restart: unless-stopped
    networks:
      - flowbit-network

networks:
  flowbit-network:
    driver: bridge
